name: Main Service deployment
on:
  push:
    branches: ["main", "eallmann/*"]
    paths:
      - '/services/main_service/**'
  pull_request:
    branches: [ "main" ]
jobs:
  deploy_main_service:
    runs-on: api-server-runner
    defaults:
      run:
        working-directory: ./services/main_service/api
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3
      - name: Make the script files executable
        run: chmod +x *.sh
      - name: Run the auth_service install script
        run: ./main_service_install.sh
