name: UI deployment
on:
  push:
    branches: ["main", "eallmann/*"]
    paths:
      - '/code/ui/leet-meet/**'
  pull_request:
    branches: [ "main" ]
jobs:
  deploy_ui:
    runs-on: ui-pipeline
    defaults:
      run:
        working-directory: ./code/ui/leet-meet
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3
      - name: Make the script files executable
        run: chmod +x *.sh
      - name: Run the ui install script
        run: ./ui_install.sh
